name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install numpy scipy matplotlib

      - name: Lint (basic) – optional
        run: |
          pip install ruff
          ruff check . || true

      - name: Prepare output dirs
        run: |
          mkdir -p out_2d artifacts

      - name: Run 2D demo smoke test
        run: |
          if [ -f nmsi_nse2d_demo.py ]; then             python nmsi_nse2d_demo.py --config config.yaml --out out_2d/timeseries.csv || true;           else             echo "nmsi_nse2d_demo.py not found – skipping.";           fi

      - name: Archive diagnostics (if any)
        run: |
          if ls out_2d/* 1> /dev/null 2>&1; then             cp -r out_2d artifacts/out_2d;           fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: artifacts/**
          if-no-files-found: warn
