grid:
  nx: 64
  ny: 64
  nz: 64
  Lx: 6.283185307
  Ly: 6.283185307
  Lz: 6.283185307
time:
  t_end: 2.0
  cfl: 0.4
  dt_min: 0.0001
  dt_max: 0.05
  save_every: 10
physics:
  nu: 0.001
forcing_pi:
  A_pi: 0.1
  omega_pi: 4.0
  phi: 0.0
  k1: 4.0
  k2: 6.0
  bandpass: true
  use: true
gamma_diss:
  gamma0: 0.05
  omega_Z: 2.0
  phiZ: 0.0
  zeta: 0.0
  use: true
  spatial_mask: false
dealias:
  use: true
io:
  outdir: ./out_3d
