name: Run NMSI Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # NB tooling
          pip install papermill jupyter nbformat nbconvert matplotlib numpy pandas

      - name: Prepare output dirs
        run: |
          mkdir -p artifacts
          mkdir -p out_3d out_2d  # optional, if notebooks expect these

      - name: Execute NMSI skeleton notebook
        run: |
          papermill             "notebooks/NMSI_NS_e_Notebook_Skeleton.ipynb"             "artifacts/NMSI_NS_e_Notebook_Executed.ipynb"             -p path "out_3d/timeseries.npz"             -p compare_paths "{}"

      - name: Convert notebook to HTML
        run: |
          jupyter nbconvert --to html "artifacts/NMSI_NS_e_Notebook_Executed.ipynb"             --output "NMSI_NS_e_Notebook_Executed.html"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmsi-notebook-results
          path: artifacts/**
          if-no-files-found: warn
