name: Tiny 3D TGV Sanity-Check
on: [push, pull_request, workflow_dispatch]
jobs:
  tgv3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install numpy scipy matplotlib
      - run: mkdir -p artifacts out_3d
      - run: python nmsi_nse3d_tg.py --config config.yaml --grid 64 --t_end 2.0 --use_e spectral || true
      - run: cp -r out_3d artifacts/out_3d || true
      - uses: actions/upload-artifact@v4
        with:
          name: tgv3d-sanity
          path: artifacts/**
